language: python
python:
  - "3.5"
env:
  - GITHUB_TOKEN="16604cd895a94970ea9bf5708854c64f71072dd4"
install:
  - "pip install ."
script: 
  - "octohatrack LABHR/octohatrack"
  - "python octohatrack.py LABHR/octohatrack-rb --no-cache"
  - "python octohatrack.py programminghistorian/jekyll -w"
